### ISSUE TITLE
Two-Way Control

### ISSUE THREAD

**Issue by mdchristians** [meliorence/react-native-snap-carousel#202]
## Feature Request: Two-way Control
It would be very cool to see the ability to have two-way control between a main component and a pagination or another component. The example I'm trying to describe can be seen here: [Swiper's Thumbs Gallery With Two-way Control](http://idangero.us/swiper/demos/300-thumbs-gallery.html).

**Comment by bd-arc** [comment]
Hi @mdchristians,

This should be achievable without too much pain. Note that the two-way control between the carousel and the pagination already exists (take a look at [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example), in which the dots are tappable).

I'll try to write an example with two carousels as soon as I can ;-)

**Comment by mdchristians** [comment]
Hey @bd-arc

Thanks for the quick response!  I've done something semi-close using `snapToItem`and `onSnapToItem` with two carousels, but I can't seem to get both carousels to scroll with each other, like in the Swiper example I provided.

I look forward to the example!

**Comment by Donhv** [comment]
@bd-arc Have example for two-way control like this:
![screen shot 2018-02-09 at 2 04 27 pm](https://user-images.githubusercontent.com/16864971/36081878-a32e352e-0fd6-11e8-81aa-38ddc5c0f794.png)

If not how to make button previous & next like Application Demo: 
https://camo.githubusercontent.com/3bd921828eba131cf78d3e6fc5123abb3e9045ab/68747470733a2f2f692e696d6775722e636f6d2f466f706533756a2e676966

Many thanks

**Comment by bd-arc** [comment]
@Donhv Implementing a two-way control example is clearly on my roadmap. Take a look at #257 to get a sneak peek at the miscellaneous examples I want to add.

Still, I didn't have much time recently to work on it. You'll have to wait a bit longer...

**Comment by dohooo** [comment]
Sorry, please allow me to advertise for my open source library! ~
I think this library [react-native-reanimated-carousel](https://github.com/zwh1666258377/react-native-reanimated-carousel) will solve your problem. It is a high performance and very simple component, complete with React-Native reanimated 2
