### ISSUE TITLE
Autoplay doesn't work after scrolling one loop with vertical property

### ISSUE THREAD

**Issue by LeviDeng** [meliorence/react-native-snap-carousel#353]
### Environment
    React: 16.0.0-alpha.12
    React native: 0.54.4
    react-native-snap-carousel: 3.7.2

### Target Platform:
    Android (7.0)
    iOS (10.3)

### Steps to Reproduce
```jsx
<Carousel
  loop={true}
  autoplay={true}
  vertical={true}
  sliderWidth={36}
  itemHeight={36}
  data={/*just two item*/}
  ...
/>
```

### Actual Behavior
Autoplay doesn't work after scrolling one loop

**Comment by bd-arc** [comment]
Hi @MelonDeng,

Could you please share a simple [Snack example](https://snack.expo.io/) that reproduces the issue?

**Comment by MelonDeng** [comment]
@bd-arc sure, here it is:
https://snack.expo.io/rkgnecBmQ

The Carousel can't loop back after scrolling at the last one

**Comment by Ding95** [comment]
same issue

**Comment by bd-arc** [comment]
@MelonDeng @Ding95 Just a quick update: I'm currently working on replacing the `FlatList` component with another one. My hope is to make this kind of irritating bug disappear completely.

I'll keep you posted!

**Comment by StephentTom** [comment]
same issue

**Comment by pandrawla** [comment]
same issue

**Comment by Xaber20110202** [comment]
Same issue, I tried many props, cost almost 6 hours, I tested this:

Set `sliderHeight`, `itemHeight` to 41 (50, or larger), it works.

**Comment by wxsms** [comment]
@Xaber20110202 life saver. thank you very much.

**Comment by dohooo** [comment]
Sorry, please allow me to advertise for my open source library! ~
I think this library [react-native-reanimated-carousel](https://github.com/zwh1666258377/react-native-reanimated-carousel) will solve your problem. It is a high performance and very simple component, complete with React-Native reanimated 2
