### ISSUE TITLE
Android doesn't fire snap event for the last item when scrolled all the way

### ISSUE THREAD

**Issue by dbilgin** [meliorence/react-native-snap-carousel#681]
### Is this a bug report, a feature request, or a question?

This is a bug report, I have seen [this](https://github.com/archriss/react-native-snap-carousel/issues/159) but I am doubtful that it's the same thing.

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

It's only on Android.

### Is the bug reproductible in a production environment (not a debug one)?

Yes, tried it with an assembled apk.

### Environment

    React: 16.8.6
    React native: 0.60.5
    react-native-snap-carousel: 3.9.0
    Android: Seems to be all Android versions

### Expected Behavior

When I swipe to the very last item I expect the snap events to fire even if I didn't stop my finger immediately when the swipe was in place and that I wouldn't have to nudge the carousel again to make it work.

### Actual Behavior

![reproduce](https://user-images.githubusercontent.com/15243788/78889310-baa5cb00-7a63-11ea-9844-ccea8775ea96.gif)

### Reproducible Demo

Here is the [demo](https://snack.expo.io/@aegletes/react-native-snap-carousel-android-bug)

### Steps to Reproduce

I think the steps are fairly simple

1. Create a carousel smaller than the width of the screen with three views in it.
2. Move to the middle view.
3. Move to the third view starting to hold it from the very right of the screen and not the third view itself and swipe it to the very left.

**Comment by vincentzierigen** [comment]
Having the same issue with RN 6.0.4

**Comment by CoenWarmer** [comment]
Having the same issue (RN 0.61.4). Any workaround available before a fix is deployed?

**Comment by dbilgin** [comment]
I couldn't find any workarounds so far, would actually appreciate it very much, if someone did.

**Comment by CoenWarmer** [comment]
@dbilgin Haven't found one yet, unfortunately.

**Comment by CoenWarmer** [comment]
I believe the same happens on Android when scrolling past the first item. The callback isn't fired then either.

**Comment by nitaking** [comment]
My solution: 
1. Add empty data ([data, data, {}]] 
2. `if (lastIndex === 2 ) { this.onEnd() }`

**Comment by luka-iyarn** [comment]
Have the same issue with first item as well.
This worked for me:
`enableMomentum={Platform.OS === 'android'}`

**Comment by dbilgin** [comment]
@luka-iyarn that doesn't fix it for me unfortunately.

**Comment by CoenWarmer** [comment]
@bd-arc thank you for your work on the library! It is by far the best carousel library for RN out there.

Is this particular bug on Android something that you want to address in version 4, or is this something that can be fixed in the current 3.x approach?

**Comment by bd-arc** [comment]
Hey guys! Did any of you tried the 4.x beta version? (the latest one being `4.0.0-beta.5`)

Since the carousel has been heavily updated, it *might* now work out-of-the box. Scroll events on Android have always been unreliable, but I'm hoping that the improved logic will fix your issue.

Let me know!

**Comment by dbilgin** [comment]
@bd-arc thank you for your response! I just tried it on my project again with `4.0.0-beta.5`, somehow it got worse :( Now it doesn't snap to the second one even.

**Comment by roybselim** [comment]
I ended up creating a custom logic on 'onScroll'

          onScroll={(event) => {
            const currentOffset = event.nativeEvent.contentOffset.x;
            if (onPress && answers && Array.isArray(answers)) {
              if (currentOffset === 0) {
                onPress(answers[0]);
              }
              if (currentOffset >= ITEM_WIDTH * (answers.length - 1) - 5) {
                onPress(answers[answers.length - 1]);
              }
            }
          }}

**Comment by dohooo** [comment]
Sorry, please allow me to advertise for my open source library! ~
I think this library [react-native-reanimated-carousel](https://github.com/zwh1666258377/react-native-reanimated-carousel) will solve your problem. It is a high performance and very simple component, complete with React-Native reanimated 2

**Comment by dbilgin** [comment]
Just gonna go with FlatList.
