### ISSUE TITLE
onSnapToItem prop not working

### ISSUE THREAD

**Issue by 16ntu1120** [meliorence/react-native-snap-carousel#792]
I just wanted to get the index when I move forward and backward using my hand. But onSnapToItem is not doing anything whenever I try to do this. Help needed

**Comment by khalidkaram** [comment]
Can you share your code?

**Comment by 16ntu1120** [comment]
@khalidkaram  I've solved the issue.

**Comment by Romick2005** [comment]
If you solve the issue then please close this as your code fault.

**Comment by Marinaarimany** [comment]
> @khalidkaram I've solved the issue.

Hello @khalidkaram , I have the same problem, can you tell me how did you manage to solve this problem please
