### ISSUE TITLE
snapToNext method not working

### ISSUE THREAD

**Issue by 16ntu1120** [meliorence/react-native-snap-carousel#793]
Whenever I try to work with this method error occurred that is "carousel" is not defined need help?

**Comment by 256hz** [comment]
I'm not a maintainer of the library, just a user, but are you passing the Carousel ref to the Pagination component?  See the `carouselRef` prop in the [Pagination docs](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PAGINATION.md#props)[].

**Comment by eduardopelitti** [comment]
@16ntu1120 Please provide code examples!

**Comment by 16ntu1120** [comment]
@eduardopelitti I resolved this issue I was missing the ref prop as @256hz said closing this issue.
